language: python
arch:
    - amd64
    - ppc64le
addons:
  apt:
    packages:
    - zlib1g-dev
    - libblas-dev
    - liblapack-dev
    - libgfortran3
    - libncurses5-dev
python:
- '3.6'
sudo: false
install:
- pip install pysam
- source ./install_dependencies.sh
before_script:
- pip install codecov
script:
- coverage run setup.py test
after_success:
- codecov
